# California Housing

- Number of Instances: 20640

- Number of Attributes: 8 numeric, predictive attributes and the target

- Attribute Information:
  - MedInc        median income in block group
  - HouseAge      median house age in block group
  - AveRooms      average number of rooms per household
  - AveBedrms     average number of bedrooms per household
  - Population    block group population
  - AveOccup      average number of household members
  - Latitude      block group latitude
  - Longitude     block group longitude
  
- Missing Attribute Values: None

## Setps going forward

1. Collect data
2. Normilize, get all data to same scale
3. Chose validation method, here hold-out validation
4. Chose activation function, here linear
5. Chose model selection, here multilayer perceptron

In [1]:
# Imports
import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import normalize, MinMaxScaler
import matplotlib.pyplot as plt

In [2]:
# View some of the data
housing_data = fetch_california_housing(as_frame=True)
print('Input features:\n',housing_data.data.head())
print('Target feature:\n',housing_data.target.head())

x = housing_data.data
y = housing_data.target

# Normalize the input features (attributes)
scalar = MinMaxScaler()
xn = scalar.fit_transform(x)
print('minmax scalar:\n', xn)   # MinMaxScaler is applied column-wise (normalize each column)

# Split data into train and test sets
xtrain, xtest, ytrain, ytest = train_test_split(xn, y, test_size=0.2, random_state=42)
print(len(xtrain))

print(xtrain.shape, xtest.shape)
print(ytrain.shape, ytest.shape)

Input features:
    MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25  
Target feature:
 0    4.526
1    3.585
2    3.521
3    3.413
4    3.422
Name: MedHouseVal, dtype: float64
minmax scalar:
 [[0.53966842 0.78431373 0.0435123  ... 0.00149943 0.5674814  0.21115538]
 [0.53802706 0.39215686 0.03822395 ... 0.00114074 0.565356   0.21215139]
 [0.46602805 1.         0.05275646 ... 0.00169796 0.5642933  0.21015936]
 ...
 [0.08276438 0.31372549 0.03090386 ... 0.0013144  0.73219979 0.31175299]
 [0.09429525 0.33

In [2]:
# Building the multilayer perceptron
from tensorflow import keras
from tensorflow.keras import layers
from keras.models import Sequential

model = Sequential([
    layers.Dense(64, activation='relu', input_shape=[8]),
    layers.Dense(16, activation='relu'),
    layers.Dense(1)   #  By default, activation function is set to None. That means that by default it is a linear activation.
])

model.compile(optimizer='rmsprop', loss='mse', metrics=['mse','mae','accuracy'])


Using TensorFlow backend.


TypeError: The added layer must be an instance of class Layer. Found: <tensorflow.python.keras.layers.core.Dense object at 0x7f859772f250>